
FROM alpine:3.20

# Install tools
RUN apk add --no-cache curl bash busybox-suid

# Set working directory
WORKDIR /app

# Copy scripts into container
COPY trainer_utils/ /app/trainer_utils/

# Make scripts executable
RUN chmod +x /app/trainer_utils/*.sh

# Default command → start cron setup script
CMD ["sh", "/app/trainer_utils/run_training.sh"]