{
 "title": "MY_PROVISIONED_DASHBOARD",
 "description": "Dashboard of the movie recommenddation system of the Datascientest project.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "System Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Inflight Requests",
   "type": "stat",
   "description": "Number of HTTP requests that are currently being processed by the API at this moment. This metric indicates the current system load and shows how many requests are running concurrently.",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(http_requests_in_flight)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "API latency (p95)",
   "type": "timeseries",
   "description": "95th percentile of the HTTP request duration for the API. This metric shows how long API requests take to complete, where 95% of all requests finish within this time.",
   "gridPos": { "h": 8, "w": 12, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\r\n    sum(rate(http_request_duration_seconds_bucket[1m])) by (le)\r\n)",
     "legendFormat": "p95 latency"
    }
   ]
  },
  {
   "title": "Error Rate (HTTP)",
   "type": "timeseries",
   "description": "Ratio of failed API requests compared to the total number of API requests. This metric indicates the reliability of the service by showing the percentage of requests that result in an error.",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status!=\"200\"}[1m])) / sum(rate(http_requests_total[1m]))",
     "legendFormat": "Error rate"
    }
   ]
  },
  { "title": "API traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "description": "Rate of incoming HTTP requests processed by the API per second. This metric indicates the current traffic level and overall load on the service.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))",
     "legendFormat": "Request rate last minute"
    }
   ]
  },
  {
   "title": "Requests per endpoint",
   "type": "timeseries",
   "description": "Rate of HTTP requests per API endpoint. This metric shows how frequently each endpoint is called and helps identify which parts of the API are most actively used.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  { "title": "Recommendation Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Recommendation requests",
   "type": "timeseries",
   "description": "Rate of recommendation requests processed by the recommendation endpoint. This metric indicates how often the recommendation system is used.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expr": "rate(reco_requests_total[1m])", "legendFormat": "recommendation requests" }
   ]
  },
  {
   "title": "Recommendation latency (p95)",
   "type": "timeseries",
   "description": "95th percentile of the time required to generate movie recommendations. This metric shows how long the recommendation algorithm takes to compute results for a request.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n    0.95,\r\n    sum(rate(reco_request_duration_sec_bucket[1m])) by (le)\r\n)",
     "legendFormat": "recommendation latency"
    }
   ]
  },
  { "title": "Model Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Model served count",
   "type": "barchart",
   "description": "Total number of predictions served by each deployed model version. This metric indicates how frequently each model version is used in production.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(model_served_total) by (model_version)",
     "legendFormat": "{{model_version}}"
    }
   ]
  }
 ]
}